### ISSUE TITLE
img tags and others that aren't self closing

### ISSUE THREAD

**Issue by MMesch** [rnons/purescript-html-parser-halogen#10]
Hey all,

I think some tags aren't recognized if they aren't self-closing. E.g. `<img src="mypic.png"></img>` doesn't work whereas `<img src="mypic.png"/>` does. Not sure if this is something that should be changed. The relevant lines with tags that have to be self-closing seem to be these:

https://github.com/rnons/purescript-html-parser-halogen/blob/master/src/Html/Parser.purs#L78-L82

**Comment by rnons** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

> Must have a start tag and must not have an end tag
