### ISSUE TITLE
< tags > in code blocks

### ISSUE THREAD

**Issue by MMesch** [rnons/purescript-html-parser-halogen#12]
It seems that tags in code blocks can also cause problems similar to #11 . I fixed it by removing the tags for now. Unfortunately I can't say which elements were concerned exactly. A priori it's just a `<pre>` and then a `<code>`.

**Comment by rnons** [comment]
You mean like `<code>1 < 2</code>`? That's invalid html according to https://validator.w3.org/#validate_by_input

**Comment by MMesch** [comment]
At least chrome seems to be tolerant to this though. But you are right. I'll close this one.
