### ISSUE TITLE
Parsing katex-generated mathml

### ISSUE THREAD

**Issue by MMesch** [rnons/purescript-html-parser-halogen#13]
I am trying to parse some katex generated html:

```
<span class="katex-mathml">
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
<semantics><mrow><msup><mi>e</mi><mi>x</mi></msup><mo>=</mo><munder><mrow><mi>lim</mi><mo>⁡</mo></mrow><mrow><mi>n</mi><mo>→</mo><mi mathvariant="normal">∞</mi></mrow></munder><mo stretchy="false">(</mo><mn>1</mn><mo>+</mo><mfrac><mi>x</mi><mi>n</mi></mfrac><msup><mo stretchy="false">)</mo><mi>n</mi></msup>
<mspace width="2em"/>
<mtext>(1)</mtext></mrow><annotation encoding="application/x-tex">
e^{x} = \lim_{n \rightarrow \infty} (1 + \frac{x}{n})^n \qquad \text{(1)}
</annotation></semantics></math></span>
```

It seems it currently fails here:

```
<mspace width="2em"/>
```

and it works with this:

```
<mspace width="2em"></mspace>
```

My use case is to precompile markdown files with math and then render them.

**Comment by MMesch** [comment]
Another one is the svg path element that typically doesn't have a closing element. Katex uses svg for some glyphs (e.g. sqrt).

**Comment by MMesch** [comment]
After fixing those, parsing works fine and everything but the katex svg glyphs (e.g. for $\sqrt$) shows up. I wonder whether I would somehow need to include this one https://github.com/rnons/purescript-svg-parser-halogen to parse a file that has html _and_ inlined svg. Thoughts?

**Comment by rnons** [comment]
I will work on using DOMParser instead of purescript-string-parsers to do the parsing, will update when it's done.

**Comment by rnons** [comment]
I think this should work after c7346bdf3e2503b8b4d720ce8be187a5a2009d8a, please reopen if it doesn't, thanks.

**Comment by MMesch** [comment]
works
