### ISSUE TITLE
Can this library parse and display html with inlined svg in halogen?

### ISSUE THREAD

**Issue by MMesch** [rnons/purescript-html-parser-halogen#14]
I encountered a strange bug when reading an html file with inlined svg through this library, displaying it in halogen. It parses fine but the svg elements are invisible. I am tracking down the origin of this and can/will open a more precise bug description but for now just wanted to ask the question whether this is something to be expected because `svg` should somehow be parsed differently, e.g. with something like this https://github.com/rnons/purescript-svg-parser-halogen? If this is the case, how can I combine both libraries to read an html file with inline svg?

See #13

**Comment by MMesch** [comment]
I wonder whether this is the issue: https://www.brightec.co.uk/blog/svg-wouldnt-render

**Comment by rnons** [comment]
Fixed in c7346bdf3e2503b8b4d720ce8be187a5a2009d8a, I only saw #15 after that, thanks for reporting looking into it.

**Comment by MMesch** [comment]
Works very well now. Parsing became a lot faster as well.
