### ISSUE TITLE
Attributes don't always parse successfully

### ISSUE THREAD

**Issue by newlandsvalley** [rnons/purescript-html-parser-halogen#3]
if the __equals__ is separated by spaces or if the value is single-quoted.  Once Halogen5 is released, I'll submit a PR.

**Comment by rnons** [comment]
Thanks for reporting I have just merged halogen-5 branch to the master.

**Comment by newlandsvalley** [comment]
OK - thanks @rnons.  I have a slight problem with the PR now - I've added a few tests using test-unit but I see you're using jest (which I don't know).

**Comment by rnons** [comment]
I should merge the halogen-5 branch sooner. If you need help with jest, you can send a PR anyway, so I can take a look.

**Comment by newlandsvalley** [comment]
Perhaps I should rename my test Main to get around any merge conflict (and at least preserve my tests) and then submit the PR. Then you can take a look at it and decide what you want to retain.

**Comment by rnons** [comment]
Yeah, if the tests are not too difficult to adapt, I can add a commit onto your branch, and merge the PR from local.
