### ISSUE TITLE
Improve parse error message

### ISSUE THREAD

**Issue by rnons** [rnons/purescript-html-parser-halogen#5]
There is basically no useful error message right now.

**Comment by MMesch** [comment]
just as quick comment until there is a better solution: you can take the position, copy the html into vim and use the command `:goto <enter number>` to get the approximate position where the parser failed.

**Comment by rnons** [comment]
Changed to use DOMParser in 9a74326daa6c3b45f7a7c503e60a718d30c0cbf1, seems no error message from DOMParser, so won't fix this.
