### ISSUE TITLE
Properly handle XML escape sequences

### ISSUE THREAD

**Issue by klntsky** [rnons/purescript-html-parser-halogen#7]
`&amp;`, `&quot;`, `&#39;` `&lt;` and `&gt;` are currently rendered verbatim. This prevents me from using this library [here](https://github.com/spacchetti/purescript-docs-search/issues/15).

Could you please extend the parser to support escape sequences?

**Comment by rnons** [comment]
I'm not sure, are there other html parsers that handle html entities? Can you do unescape before passing it to `purescript-html-parser-halogen`?

**Comment by rnons** [comment]
On the other hand, where do those entities come from? 
You may want to enable the [html](https://pursuit.purescript.org/packages/purescript-markdown-it/0.2.0/docs/MarkdownIt#v:html) option of [markdown-it](https://markdown-it.github.io/markdown-it/#MarkdownIt.new)
> options:
    html - false. Set true to enable HTML tags in source.

**Comment by rnons** [comment]
Please pull the master, if the issue is not fixed, let me know. Thanks for reporting.

**Comment by klntsky** [comment]
Thank you for quick fix!

**Comment by klntsky** [comment]
Though it also allows code execution using `<script>...</script>` when used together with purescript-markdown-it-halogen.

**Comment by klntsky** [comment]
And also, there is no DOMParser for node.

**Comment by rnons** [comment]
> And also, there is no DOMParser for node.

There is a DOMParser provided by `jsdom`. But Halogen doesn't work on node anyway. Would it be better that I move `htmlDecode` from `module Html.Parser` to `module Html.Parser.Halogen`?

Or maybe change `htmlDecode` to something like
```diff
exports.htmlDecode = function(input) {
+ var DOMParser = DOMParser || (new require('jsdom').JSDOM()).window.DOMParser;
  var doc = new DOMParser().parseFromString(input, "text/html");
  return doc.documentElement.textContent;
};
```

**Comment by rnons** [comment]
I pushed https://github.com/rnons/purescript-html-parser-halogen/commit/1dd82b8e696e5f66a5199eb1c8dcff35819a404f to use jsdom on node if available.
