### ISSUE TITLE
Print out halogen code

### ISSUE THREAD

**Issue by flip111** [rnons/purescript-html-parser-halogen#8]
Instead of converting the HTML on the fly. Would it be possible to add a feature to take the HTML and print out the halogen code so it can be used during development ?

**Comment by rnons** [comment]
It's possible, but perhaps better to do it in another repo.

You can take a look at https://github.com/nonbili/svgen, especially the [Render](https://github.com/nonbili/svgen/blob/master/src/Render.purs) module, which renders SVG to Halogen code.

**Comment by rnons** [comment]
Won't fix, not in the scope of the repo.
